- name: Calculate free mem
  hosts: localhost
  tasks: 
    - name: Calculate free memory
      ansible.builtin.shell: free | grep -i mem
      register: free
    # - name: Output the variable value
    #   ansible.builtin.debug:
    #     msg: "{{ free.stdout }}"
    - name: set a fact
      ansible.builtin.set_fact:
      FREE: "{{ free.stdout | split(' ') }}"