- name: Calculate free mem
  hosts: localhost
  tasks: 
    - name: Calculate free memory
      ansible.builtin.shell: free | grep -i mem
      register: free

    - name: set a fact
      ansible.builtin.set_fact:
        FREE: "{{ free.stdout | split(' ') }}"